resources:
  jobs:
    shogi_kif_rag_main_job:
      name: shogi_kif_rag_main_job

      environments:
        - environment_key: default
          spec:
            environment_version: "4"
            dependencies:
              - "${workspace.root_path}/artifacts/.internal/shogiapp-0.1.0-py3-none-any.whl"
              - chromadb
              - sentence_transformers

      tasks:
        - task_key: silver_pipeline
          pipeline_task:
            pipeline_id: ${resources.pipelines.silver_pipeline.id}
          depends_on: []

        - task_key: gold_pipeline
          pipeline_task:
            pipeline_id: ${resources.pipelines.gold_pipeline.id}
          depends_on: 
            - task_key: silver_pipeline

        - task_key: floodgate
          environment_key: default
          python_wheel_task:
            package_name: ShogiApp
            entry_point: floodgate

        - task_key: wikipedia
          environment_key: default
          python_wheel_task:
            package_name: ShogiApp
            entry_point: wikipedia

        - task_key: chromadb
          environment_key: default
          python_wheel_task:
            package_name: ShogiApp
            entry_point: chromadb
          depends_on:
            - task_key: gold_pipeline
            - task_key: floodgate
            - task_key: wikipedia

        - task_key: streamlit_ui
          environment_key: default
          python_wheel_task:
            package_name: ShogiApp
            entry_point: streamlit_ui
          depends_on:
            - task_key: chromadb