name: cli test

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  bundle-validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: test
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: ./.github/actions/setup-databricks-cli

      - name: Run Databricks bundle validate
        run: |
          databricks bundle validate -t dev